# Generated by Django 3.0.5 on 2020-04-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_type',
            field=models.CharField(default='기타', help_text='타입을 정해주세요!', max_length=20),
        ),
    ]
